### PR TITLE
Use `sql` instead of `compiled_code` within the default `get_limit_sql` macro

### LINKED ISSUE #370: [Bug] `compiled_code` instead of `sql` within `default__get_limit_sql` macro
_Originally posted by @greghroberts in https://github.com/dbt-labs/dbt-adapters/pull/249#discussion_r1752480614_:

> @VersusFacit and @mikealfare  Looks like this line should be using the function parameter `{{ sql }}`. It works with `{{ compiled_code }}` I assume because of the [context being set in the get_show_sql macro](https://github.com/dbt-labs/dbt-core/blob/1d3d315249c81dbca70452e5a14fbfd0edad6b2a/core/dbt/task/show.py#L34), but that's likely hiding a future bug.
> 
> I could be wrong, but ran into this when providing a custom version of get_show_sql in my project.

### PR DESCRIPTION
**Pull request by dbeatty10**
resolves #370

### Problem

https://github.com/dbt-labs/dbt-adapters/pull/249#discussion_r1752480614

> @VersusFacit and @mikealfare  Looks like this line should be using the function parameter `{{ sql }}`. It works with `{{ compiled_code }}` I assume because of the [context being set in the get_show_sql macro](https://github.com/dbt-labs/dbt-core/blob/1d3d315249c81dbca70452e5a14fbfd0edad6b2a/core/dbt/task/show.py#L34), but that's likely hiding a future bug.
> 
> I could be wrong, but ran into this when providing a custom version of `get_show_sql` in my project.

### Solution

Just swap out `sql` for `compiled_code`.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-adapters/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have run this code in development, and it appears to resolve the stated issue
- [x] Tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc.)

### CODE REVIEW

**Comment by VersusFacit** [comment]
Interesting code change 🤔  

Before we merge something like this, can we get some downstream CI builds from concrete adapters that show this is correct? Adapters itself doesn't have the functional tests to give us confidence

**Comment by dbeatty10** [comment]
@VersusFacit Assuming something like [this](https://github.com/dbt-labs/dbt-postgres/pull/167/files) will do the trick?

**Comment by dbeatty10** [comment]
> @VersusFacit Assuming something like [this](https://github.com/dbt-labs/dbt-postgres/pull/167/files) will do the trick?

Assuming so, opened this draft PR to run tests against this branch: https://github.com/dbt-labs/dbt-postgres/pull/178

Does something similar need to be done on adapters other than dbt-postgres? Or is this sufficient?

**Comment by dbeatty10** [comment]
@VersusFacit all checks on dbt-postgres passed on https://github.com/dbt-labs/dbt-postgres/pull/178 -- see below for screenshot.

Does something similar need to be done on adapters other than dbt-postgres? Or is this sufficient?

image

**Comment by amychen1776** [comment]
@dbeatty10 are you able to test this out on other adapters too? That would give me more confidence

**Comment by dbeatty10** [comment]
@amychen1776 no prob here ya go:
- https://github.com/dbt-labs/dbt-redshift/actions/runs/12279664404
- https://github.com/dbt-labs/dbt-bigquery/actions/runs/12279939150
- https://github.com/dbt-labs/dbt-snowflake/actions/runs/12279964774
- https://github.com/dbt-labs/dbt-spark/actions/runs/12279965582

### Process

1. Open each of these links:
    - https://github.com/dbt-labs/dbt-redshift/actions/workflows/integration.yml
    - https://github.com/dbt-labs/dbt-bigquery/actions/workflows/integration.yml
    - https://github.com/dbt-labs/dbt-snowflake/actions/workflows/integration.yml
    - https://github.com/dbt-labs/dbt-spark/actions/workflows/integration.yml
2. Open the "Run workflow" drop down
3. Fill out the following info (placing `dbt-adapters-372` (free-form descriptive label) & `dbeatty/fix-370` (the branch name of this PR) in the right spots):
    image
4. Click the "Run workflow" button to submit
5. Click on the workflow run once it is dispatched to see the details
    image
6. Copy the URL of the workflow run into this PR
    e.g., https://github.com/dbt-labs/dbt-snowflake/actions/runs/12279964774

> [!NOTE]  
> https://github.com/dbt-labs/dbt-postgres/actions/workflows/integration.yml was not found for `dbt-postgres`, so that will needs some follow-up to standardize. But this is covered by https://github.com/dbt-labs/dbt-postgres/pull/178 for now.

**Comment by VersusFacit** [comment]
waiting on CI: 

https://github.com/dbt-labs/dbt-redshift/actions/runs/12403871491
https://github.com/dbt-labs/dbt-bigquery/actions/runs/12403881716
https://github.com/dbt-labs/dbt-postgres/actions/runs/12403895291
https://github.com/dbt-labs/dbt-snowflake/actions/runs/12403903871
https://github.com/dbt-labs/dbt-spark/actions/runs/12279965582/job/34628064793

**Review by VersusFacit — APPROVED** [review]
all CI passed. Thanks for your patience @dbeatty10 . I stayed on late to squeeze this in for the last pre-holiday release after we left you hanging ❤️

**Pull request merged**
