### PR TITLE
Correct CHANGELOG.md

### PR DESCRIPTION
**Pull request by colin-rogers-dbt**
Looks like when we accidentally release 1.8.0 for dbt-adapters we forgot to clean up the changelog

resolves #
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/#

### Checklist

- [ ] I have read [the contributing guide](https://github.com/dbt-labs/dbt-adapters/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have run this code in development, and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc.) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by mikealfare** [comment]
The [incremental files](https://github.com/dbt-labs/dbt-adapters/tree/colin-rogers-dbt-patch-1/.changes) in `.changes` need to be updated too. The entries need to be moved into the correct file and all of the 1.8 and later files need to be deleted.

**Review by dbeatty10 — APPROVED** [review]
Looks good to me.

The only other thing that stands out are no hyperlinks to the source issue/PR within the changelogs

For example, dbt-snowflake includes links like this:
image

But if we want to include those hyperlinks (I find them very handy!), that can totally be handled in a separate PR.

**Comment by mikealfare** [comment]
All of the changes are in the `paths-ignore` argument of the changelog check, hence it's not running.

**Review by dbeatty10 — APPROVED** [review]
Looks awesome 👍

**Review by mikealfare — APPROVED** [review]

**Pull request merged**
