### PR TITLE
update dbt-adapters to include unit test feature updates

### PR DESCRIPTION
**Pull request by colin-rogers-dbt**
port unit testing adapters changes from https://github.com/dbt-labs/dbt-core/pull/8411

### Checklist

- [ ] I have read [the contributing guide](https://github.com/dbt-labs/dbt-adapter/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by MichelleArk** [comment]
Looks good regarding the macro changes! Something small I noticed was that `adapterse/base/relation.py` was also updated by https://github.com/dbt-labs/dbt-core/pull/8411 and those changes don't seem to be reflected on this branch: [relation.py changes on unit testing branch](https://github.com/dbt-labs/dbt-core/pull/8411/files#diff-8b301fa58dbc12c519f4bf6e3056605c09aea9da46b21d2ec5fd979cfd4f38ad)

I don't entirely recall why/if this change was strictly necessary. I don't see any usage of the method in dbt-core so I suspect it was just a bit of clean-up to reflect the optionality of `limit` -- but @gshank may have a better recollection ([source commit of relation.py changes](https://github.com/dbt-labs/dbt-core/pull/9184/files#))

**Comment by mikealfare** [comment]
@colin-rogers-dbt Are there any associated tests that also need to move over? Should I look into that as part of the testing migration?

**Comment by colin-rogers-dbt** [comment]
> Are there any associated tests that also need to move over? Should I look into that as part of the testing migration?

@mikealfare I'm guessing so, I think that will happen naturally as part of the PR to delete dbt-adapter-tests from core/when you break out dbt-postgres

**Comment by mikealfare** [comment]
> > Are there any associated tests that also need to move over? Should I look into that as part of the testing migration?
> 
> @mikealfare I'm guessing so, I think that will happen naturally as part of the PR to delete dbt-adapter-tests from core/when you break out dbt-postgres

Sounds good. I added an item to our migration list to make sure we don't lose it. So consider the testing half of this feature as out of scope for this PR.

**Review by mikealfare — APPROVED** [review]
These look like all of the functional code changes from the linked PR.

**Pull request merged**
